Deal with merging circular duplicate suggestions
From a real world situation we call "A case of too many Agnews",
where we had duplicate suggestions for:

77394 -> 95456
64525 -> 95456
64525 -> 77394

Attempting a merge of any one of them caused a 500:

IntegrityError: duplicate key value violates unique constraint
    "duplicates_duplicatesugg_person_id_other_person_i_229d66a0_uniq"
DETAIL:  Key (person_id, other_person_id)=(64525, 77394) already exists.

Fixes #1934