deploy: Detect region and account from the env
This fixes the infra test which broke in commit `23f8d486` with the error

```
 RuntimeError: Error: Cannot retrieve value from context provider vpc-provider since account/region are not specified at the stack level. Configure "env" with an account and region when you define your stack.See https://docs.aws.amazon.com/cdk/latest/guide/environments.html for more details.
```

See https://github.com/aws/aws-cdk/issues/3082